version: "3.9"
services:
  frontend:
    build: ./frontend
    image: "nestjs"
    ports:
      - "8081:80"
    tty: true
    stdin_open: true
    depends_on:
      - backend

  backend:
    build: ./backend
    image: "nestjs-app"
    env_file:
      - ./.env
    ports:
      - "4000:3000"
    restart: on-failure 
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    # монтируем директорию ./pg-data основной ОС в директорию с данными в контейнере
     - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
